---
- name: Secure Networking (Hardware Port Management & Docker Patch)
  hosts: all
  become: yes
  vars:
    # 'harden' -> Secure ports (delete extra) & Install ufw-docker patch (present)
    # 'revert' -> Open ports (limitless) & Remove ufw-docker patch (absent)
    mode: 'harden' 

  tasks:
    - name: "WRAPPER: Debug Mode"
      debug:
        msg: "Executing Secure Networking in {{ mode | upper }} mode."

    # 1. Run Port Management
    - name: "WRAPPER: Execute Port Management"
      import_playbook: port_management.yml
      vars:
        mode: "{{ mode }}"

    # 2. Run UFW-Docker Setup
    - name: "WRAPPER: Execute UFW Docker Setup"
      import_playbook: ufw_docker_setup.yml
      vars:
        state: "{{ 'present' if mode == 'harden' else 'absent' }}"
