- name: "WRAPPER: Debug Mode"
  hosts: all
  gather_facts: no
  tasks:
    - debug:
        msg: "Executing Secure Networking in {{ mode | default('harden') | upper }} mode."

- import_playbook: port_management.yml
  tags: [ports]

- import_playbook: ufw_docker_setup.yml
  tags: [docker]
  vars:
    state: "{{ 'present' if (mode | default('harden')) == 'harden' else 'absent' }}"
