---
- name: Find Node Running ViralReel Service
  hosts: swarm_managers[0]
  gather_facts: yes
  vars:
    service_name_pattern: "viralreel-appapi"
  tasks:
    - name: Find Service ID
      shell: "docker service ls --filter 'name={{ service_name_pattern }}' --format '{{ '{{' }}.ID{{ '}}' }}'"
      register: service_id_output
      changed_when: false

    - name: Log Service ID Finding
      debug:
        msg: 
          - "Command: docker service ls --filter 'name={{ service_name_pattern }}'"
          - "Output: {{ service_id_output.stdout }}"

    - name: Set Service ID
      set_fact:
        service_id: "{{ service_id_output.stdout }}"

    - name: Fail if Service Not Found
      fail:
        msg: "Service matching '{{ service_name_pattern }}' not found."
      when: service_id == ""

    - name: Find Node Name running the service
      shell: "docker service ps {{ service_id }} --filter 'desired-state=running' --format '{{ '{{' }}.Node{{ '}}' }}' | head -n 1"
      register: node_name_output
      changed_when: false

    - name: Log Node Finding
      debug:
        msg:
          - "Command: docker service ps {{ service_id }} --filter 'desired-state=running'"
          - "Output: {{ node_name_output.stdout }}"

    - name: Set Node Name
      set_fact:
        target_node_name: "{{ node_name_output.stdout }}"

    - name: Debug Target Info
      debug:
        msg: "Target Node Name: {{ target_node_name }}"

    - name: Add Target Host to Group
      add_host:
        name: "{{ target_node_name }}"
        groups: target_group
        found_service_id: "{{ service_id }}"
      # We rely on inventory.ini to provide connection details for 'target_node_name' (e.g. racknerd-66b5b59)

- name: Execute Commands on Target Node
  hosts: target_group
  gather_facts: no
  vars:
    service_name_pattern: "viralreel-appapi"
    action: "{{ action | default('credit') }}"
    # Seeding commands mapping
    seeding_commands:
      seed_plans: "node dist/db/seed-plans.js"
      seed_voices: "node dist/db/seed-voices.js"
      seed_subtitles: "node dist/db/seed-subtitles.js"
  tasks:
    - name: "VALIDATION: Verify Credit Arguments"
      fail:
        msg: "Please provide 'email' and 'amount' variables for credit action (e.g. -e 'action=credit email=x amount=y')."
      when: action == 'credit' and (email is not defined or amount is not defined)

    - name: Find Container ID
      shell: "docker ps --filter 'name={{ service_name_pattern }}' --format '{{ '{{' }}.ID{{ '}}' }}' | head -n 1"
      register: container_id_output
      changed_when: false

    - name: Log Container ID Finding
      debug:
        msg:
          - "Command: docker ps --filter 'name={{ service_name_pattern }}'"
          - "Output: {{ container_id_output.stdout }}"

    - name: Fail if Container Not Found
      fail:
        msg: "Container for service '{{ service_name_pattern }}' not found on this node."
      when: container_id_output.stdout == ""

    # Action: Credit
    - name: "EXECUTE: Give Credit Script"
      command: "docker exec {{ container_id_output.stdout }} node dist/scripts/give-credit.js {{ email }} {{ amount }}"
      register: credit_output
      when: action == 'credit'

    - name: "LOG: Credit Script Output"
      debug:
        msg:
          - "Command: docker exec {{ container_id_output.stdout }} node dist/scripts/give-credit.js {{ email }} {{ amount }}"
          - "Output:"
          - "{{ credit_output.stdout_lines }}"
      when: action == 'credit'

    # Action: Individual Seeding
    - name: "EXECUTE: Seeding Command ({{ action }})"
      command: "docker exec {{ container_id_output.stdout }} {{ seeding_commands[action] }}"
      register: seed_output
      when: action in seeding_commands

    - name: "LOG: Seeding Output ({{ action }})"
      debug:
        msg:
          - "Command: docker exec {{ container_id_output.stdout }} {{ seeding_commands[action] }}"
          - "Output:"
          - "{{ seed_output.stdout_lines }}"
      when: action in seeding_commands

    # Action: Seed All
    - name: "EXECUTE: Seed All Commands"
      command: "docker exec {{ container_id_output.stdout }} {{ item.value }}"
      register: seed_all_outputs
      loop: "{{ seeding_commands | dict2items }}"
      when: action == 'seed_all'

    - name: "LOG: Seed All Outputs"
      debug:
        msg:
          - "Command: docker exec {{ container_id_output.stdout }} {{ item.cmd[-1] }}"
          - "Output:"
          - "{{ item.stdout_lines }}"
      loop: "{{ seed_all_outputs.results }}"
      when: action == 'seed_all' and not item.skipped | default(false)
